from typing import Any, Protocol

class ClockDevice(Protocol):
    def clock(self, cycles: int) -> None: ...

class InputDevice(Protocol):
    def input_handler(self, key: Any, pressed: Any) -> None: ...

class PortDevice(Protocol):
    def port_handler(self, port: int, mask: int, value: int) -> None: ...

class SerialRxDevice(Protocol):
    def serial_rx_handler(self, data: Any) -> None: ...

class Emulator(Protocol):
    def audio_handler(self, channel: int, data: Any) -> None: ...
    def serial_tx_handler(self, data: Any) -> None: ...

class Interconnect:
    _clock_devices: list[ClockDevice]
    _input_devices: list[InputDevice]
    _port_devices: list[PortDevice]
    _serial_rx_devices: list[SerialRxDevice]
    _emulator: Emulator

    def __init__(self, emulator: Emulator) -> None: ...
    def register_port_device(self, dev: PortDevice) -> None: ...
    def emit_port(
        self, sender: PortDevice, port: int, mask: int, value: int
    ) -> None: ...
    def register_input_device(self, dev: InputDevice) -> None: ...
    def emit_input(self, key: Any, pressed: Any) -> None: ...
    def register_clock_device(self, dev: ClockDevice) -> None: ...
    def emit_clock(self, cycles: int) -> None: ...
    def register_serial_rx_device(self, dev: SerialRxDevice) -> None: ...
    def emit_serial_rx(self, data: Any) -> None: ...
